stages:
- stage: continousintegration
  displayName: Continous integration
  jobs:
  - job: build
    displayName: Build 
    steps:
    - script: dotnet restore
      displayName: restore
    - script: dotnet build
      displayName: build
    - script: dotnet test
      displayName: test
    - script: dotnet publish
      displayName: publish
        


